### ISSUE TITLE
file missing

### ISSUE THREAD

**Issue by mouad47** [henritomas/ssd-keras#4]
thank you for this work i really i appreciate it.
where can i find this file 'ssd_vgg_epoch-10_loss-3.02_val_loss-3.05.h5' ? emilia_mobileNet ??

**Comment by henritomas** [comment]
Hello!

Apologies for the messy documentation, I have been working on another project so I haven't come around to documenting this repository properly.

There are two ways of initiating the model (you only have to run one of them):
#1 build the model and load the weights.
-This is for starting the training: it builds the model architecture and loads the Imagenet trained weights. 
#1.2 Load an h5 model.
-This is for continuing training after saving the model from previous training. Loading the model is good because optimizer state is saved so training seamlessly continues from where it left off. 
-This is also for loading a model for evaluation or inference. 

The file you are asking for is #1.2, when I was continuing my training, which you shouldn't need if you plan on training the ssd model from scratch. However if you want the trained model to load for inference, you can download and load this: 

https://drive.google.com/file/d/10DWGNbJUdEh7uMbmiXPDa9s0UiiOWAj4/view?usp=sharing

this is ssd-mobilenet trained on PASCAL VOC 2007 and 2012, achieving 62.3 mAP on 2007 test set.

**Comment by mouad47** [comment]
thank you @henritomas  it was very helpful
another file is missing,where can i find this file please.
"ssd_vgg_training_log.csv"

**Comment by henritomas** [comment]
A csv file is written out to record the training and validation loss by Keras after training the model (running the model.fit_generator cell) , the file itself is not available if you haven't trained the model yet.

**Comment by mouad47** [comment]
so i have to create my own csv file ! i found the same file in other repository on github,it's working.
but another problem has appeared again,
DegenerateBatchError: You produced an empty batch.....ect
so i changed the scripts a little bit and the training started normally until this error has shown up:
Error when checking input: expected input_1 to have shape (300, 300, 3) but got array with shape (224, 224, 3)

 if you have any idea about it please help, thank you
note:
I'm using a different dataset, the size of the images is (224,224,3)
